// Generated by CoffeeScript 1.6.3
var left, move, right, walkRight, x;

walkRight = true;

left = 400;

right = 700;

x = left;

move = function() {
  var img;
  img = document.getElementsByTagName("img")[0];
  if (walkRight) {
    x += 5;
  }
  if (!walkRight) {
    x -= 5;
  }
  img.style.left = x + "px";
  if (x > right || x < left) {
    img.classList.toggle("flip-img");
  }
  if (x < left) {
    walkRight = true;
  }
  if (x > right) {
    return walkRight = false;
  }
};

setInterval(move, 100);
